# Generated by Django 4.1.6 on 2023-03-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reciepes", "0003_remove_ingredient_reciepe_reciepe_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="user_ingredient",
            new_name="user",
        ),
    ]
